In [1]:
import pandas as pd
import numpy as np
import glob
from tqdm import notebook as tqdm_notebook

In [8]:
pathto_parquets = glob.glob('assignment_600519/book/600519/*.gzip')

In [9]:
dfs = []
for pathto_parquet in pathto_parquets:
    df = pd.read_parquet(pathto_parquet)
    dfs.append(df)
df = pd.concat(dfs).reset_index(drop=True)
df.head()

,TimeStamp,Bid1,Bid1Size,Ask1,Ask1Size,Bid2,Bid2Size,Ask2,Ask2Size,Bid3,...,Bid4,Bid4Size,Ask4,Ask4Size,Bid5,Bid5Size,Ask5,Ask5Size,midpt,nextMidpt
0,1585704603505567,1113.00,1900,1115.03,100,1112.22,2800,1116.00,500,1112.00,...,1111.21,3000,1117.99,8358,1111.11,1600,1118.0,1300,1114.015,1115.265
1,1585704606961840,1115.03,100,1115.50,100,1114.44,200,1117.00,940,1113.01,...,1113.00,1900,1117.40,4000,1112.22,2800,1117.5,100,1115.265,1116.495
2,1585704609513298,1116.00,1600,1116.99,100,1115.03,300,1117.00,1240,1114.44,...,1113.01,600,1117.40,4000,1113.00,2000,1117.5,100,1116.495,1113.795
3,1585704612124381,1113.15,300,1114.44,400,1113.01,600,1116.99,100,1113.00,...,1112.22,2800,1117.40,4000,1112.00,1600,1117.5,100,1113.795,1111.565
4,1585704615123840,1111.51,100,1111.62,2200,1111.50,200,1116.00,100,1111.30,...,1111.21,3000,1117.00,300,1111.18,200,1117.4,4000,1111.565,1114.200